### PR TITLE
Version 0.1.0 features

### PR DESCRIPTION
**Pull request by nattfodd**
To understand what's going on, I would recommend to start from the following items:
* Usage example: https://github.com/nattfodd/transcryptor_sample_app/pull/2/files
* README - https://github.com/riboseinc/versioned_fields/blob/0ea6e93604603291788085fbc3ceb4443624ee02/README.adoc

- [x] Design migrations DSL
- [x] Implement migration DSL inner guts
- [x] Create railtie for loading migrations
- [x] Update README
- [x] Write tests

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @nattfodd ! @ribose-jeffreylau will be reviewing this too

**Comment by nattfodd** [comment]
Ok, just want to specify this is still early work in progress. I let you know once it's ready for review :)

**Comment by nattfodd** [comment]
Hey, guys. PR is ready to be reviewed :)

**Comment by ronaldtse** [comment]
Thanks @nattfodd ! I'd like to request some minor changes to the README.

I'd like to clarify in the README that the version block is run on every single cell when accessed, even when the underlying data hasn't migrated ("saved") yet.

```ruby
VersionedFields::Migration.draw_for(User, :address) do
  version 1
  version 2 do |prev_value|
    ...
  end
end
```

For example, even if the value of `User.find(2).address` is actually still at V1 in the database, the result of `User.find(2).address` always returns the V2 value regardless if it has been "upgraded" (because "upgrading" involves writing, but "accessing" only involves reading).

What do you think?

**Comment by nattfodd** [comment]
@ronaldtse thanks! Not sure I got your point. In a current implementation, calling User.find(2) will migrate & **write** to the DB changes if any field migrations were pending for record with `ID=2`. 

While migration is running (under the hood) there's no point to save field every time we upgrade field's value from one version to another. So it's better to run migrations one by one, and once all migrations are completed, then we update the record in a DB, and return found object.

**Comment by ronaldtse** [comment]
@nattfodd right. I wasn't sure on the order of the "read" and "write" operations -- if we always "write" the new version first, the subsequent reads must always be correct.

**Comment by nattfodd** [comment]
I've added a few paragraphs about that to README (see latest commit)

**Comment by ronaldtse** [comment]
@nattfodd feel free to merge, thanks! Next step is to have Transcryptor use this 👍

**Pull request merged**
